### ISSUE TITLE
doesn't require subdirectories

### ISSUE THREAD

**Issue by Janpot** [aseemk/requireDir#41] opened 2016-09-12 15:53 UTC
currently I have the following situation:

```
/foo/bar.js
/foo/baz/index.js
/foo/baz/bar.js
```

what I'm expecting when I do 

``` js
requireDir('./foo');
```

is

``` js
{
  bar: '...',
  baz: '...'
}
```

like it follows the semantics of `require` with respect to subfolders, but what I get is 

``` js
{
  bar: '...'
}
```

while the `recurse` options is not what I want because that would give me:

``` js
{
  bar: '...',
  baz: {
    index: '...',
    bar: '...'
  }
}
```

**Comment by contra** [comment] 2018-02-07 22:56
closing, duplicate of https://github.com/aseemk/requireDir/pull/23

**Closed by contra** 2018-02-07 22:56 UTC
